#!/bin/sh
# add-tenant.sh — register a tenant on the fdb-ingest gateway and restart it.
#
#   ./add-tenant.sh cliente2 replica_cliente2
#   ./add-tenant.sh cliente2            # db defaults to replica_<cn>
#
# Tenants live in tenants.conf (one "CN=database" per line); this script keeps it
# deduped and regenerates the systemd unit's ExecStart from it. The client cert is
# issued elsewhere (the machine holding ca.key, e.g. issue-tenant.ps1) — only
# ca.crt is needed here. Installed on the dev gateway at /root/fdb-ingest/.
set -eu

DIR=/root/fdb-ingest
UNIT=/etc/systemd/system/fdb-ingest.service
CONF=$DIR/tenants.conf

cn=${1:?usage: add-tenant.sh <CN> [database]}
db=${2:-replica_$cn}

case "$cn" in *=*) echo "CN must not contain '='" >&2; exit 1;; esac

touch "$CONF"
# Drop any existing entry for this CN, then add the new mapping.
tmp=$(mktemp)
grep -v "^$cn=" "$CONF" > "$tmp" || true
echo "$cn=$db" >> "$tmp"
sort -u "$tmp" -o "$CONF"
rm -f "$tmp"

# Build the --tenant lines from the conf.
tenants=""
while IFS= read -r line; do
    [ -n "$line" ] || continue
    tenants="$tenants    --tenant $line \\
"
done < "$CONF"

cat > "$UNIT" <<UNIT
# fdb-ingest gateway — dev box. Generated by add-tenant.sh; edit tenants.conf + rerun.
[Unit]
Description=fdb-ingest — Firebird->PostgreSQL push gateway (mTLS)
After=network-online.target postgresql.service
Wants=network-online.target

[Service]
Type=simple
WorkingDirectory=$DIR
ExecStart=$DIR/fdb-ingest serve \\
    --bind 0.0.0.0:8443 \\
    --ca   $DIR/pki/ca.crt \\
    --cert $DIR/pki/server.crt \\
    --key  $DIR/pki/server.key \\
    --pg-host 127.0.0.1 --pg-port 5432 --pg-user postgres --pg-password postgres \\
$tenants
Restart=on-failure
RestartSec=3
NoNewPrivileges=true

[Install]
WantedBy=multi-user.target
UNIT

systemctl daemon-reload
systemctl restart fdb-ingest
echo "tenant '$cn' -> '$db' registered. current tenants:"
cat "$CONF"
sleep 1
systemctl --no-pager status fdb-ingest | grep -E 'Active:|listening' || true
